/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yokes
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import dao.Connecter;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class AddMedicine extends javax.swing.JFrame {
    public String pp =  "^[0-9]+(\\.[0-9]{1,2})?$";;
    public int ip = 0;
    public String quanp = "^[1-9]\\d*$";


    /**
     * Creates new form AddMedicine
     */
    public AddMedicine() {
        initComponents();
        clabel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mntext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cntext = new javax.swing.JTextField();
        ptext = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        clabel = new javax.swing.JLabel();
        mtcombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        qt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ADD MEDICINE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        mntext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mntextKeyReleased(evt);
            }
        });
        getContentPane().add(mntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 201, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Medicine Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Medicine Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Comapany Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        cntext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cntextActionPerformed(evt);
            }
        });
        getContentPane().add(cntext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 193, -1));
        getContentPane().add(ptext, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 198, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Price/unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, -1, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, 49));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1010, 10));
        getContentPane().add(clabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 40, 20));

        mtcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Syrup", "Injection", "Capsule" }));
        getContentPane().add(mtcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));
        getContentPane().add(qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 190, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cntextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cntextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cntextActionPerformed

    private void mntextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mntextKeyReleased
        // TODO add your handling code here:
    String mname = mntext.getText();  
    if(!mname.equals("")){
        clabel.setVisible(true);
        clabel.setIcon(new ImageIcon("src\\Images\\yes.png"));
        clabel.setText("");
        ip = 0;
        
        try{
            Connection con = Connecter.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from drugs where drug_name = '"+mname+"'");
            while(rs.next()){
                ip = 1;
                clabel.setIcon(new ImageIcon("src\\Images\\no.png"));
                clabel.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }
    else{
        clabel.setVisible(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_mntextKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type = (String) mtcombo.getSelectedItem();
        String mname = mntext.getText();
        String cname = cntext.getText();
        String price = ptext.getText();
        String q = qt.getText();
        if(mname.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is Must");
        }else if(cname.equals("")){
            JOptionPane.showMessageDialog(null,"Company Name field is Must");
        }else if(price.equals("")){
            JOptionPane.showMessageDialog(null,"Price field is Must");
        }else if(q.equals("")){
            JOptionPane.showMessageDialog(null,"Qunatity field is Must");
        }else if(!q.matches(quanp)){
            JOptionPane.showMessageDialog(null,"Quantity field is Invalid");
        }else if(!price.matches(pp)){
            JOptionPane.showMessageDialog(null,"Price field is Invalid");
        }else if(ip==1){
            JOptionPane.showMessageDialog(null,"Medicine already Exist");
        }else{
        try{
            int x = Integer.parseInt(q);
            Connection con = Connecter.getCon();
                PreparedStatement ps = con.prepareStatement("insert into drugs(drug_name,drug_type,company_name,price,quantity) values(?,?,?,?,?)");
                ps.setString(1, mname);
                ps.setString(2, type);
                ps.setString(3, cname);
                ps.setString(4, price);
                ps.setInt(5,x);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Medcine added Successfully.");
                setVisible(false);
                new AddMedicine().setVisible(true);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
         //new PharmacistDashboard().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clabel;
    private javax.swing.JTextField cntext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mntext;
    private javax.swing.JComboBox<String> mtcombo;
    private javax.swing.JTextField ptext;
    private javax.swing.JTextField qt;
    // End of variables declaration//GEN-END:variables
}
