
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.Connecter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.io.FileOutputStream;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import java.util.Calendar;
import java.util.*;
import pack.Open;
import dao.Loco;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yokes
 */
public class SellMedicine extends javax.swing.JFrame {
    private String np = "^[0-9]{10}$";
    private double tp=0.0;
    private String bid="";
    private String un="";
    public String uid = ""; 
    public int pts = 0;
    public String cuid = "";

    /**
     * Creates new form SellMedicine
     */
    public SellMedicine() {
        initComponents();
    }
    public SellMedicine(String uname) {
        initComponents();
        un=uname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        mq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cart = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        tpfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        mt = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        custid = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("SELL MEDICINE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 23, 291, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Medicine id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        getContentPane().add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 210, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 246, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Medicine Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 421, 84, -1));
        getContentPane().add(mp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 210, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Price/Unit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, 24));
        getContentPane().add(mq, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("No.of Unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 100, -1));

        mid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midActionPerformed(evt);
            }
        });
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 209, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, -1, -1));

        cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer id", "Medicine ID", "Medicine Name", "Company name", "Price/Unit", "Quantity", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cart);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 740, 550));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("PRINT BILL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 690, -1, -1));

        tpfield.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tpfield.setText("00.00");
        getContentPane().add(tpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 710, 71, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 710, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Company Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));
        getContentPane().add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 210, -1));

        mt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Syrup", "Injection", "Capsule" }));
        getContentPane().add(mt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Customer ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        getContentPane().add(custid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 200, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void midActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midActionPerformed
private void clearmed(){
    mid.setText("");
    mn.setText("");
    custid.setText("");
    cn.setText("");
    mt.removeAllItems();
    mt.addItem("Tablet");
    mt.addItem("Syrup");
    mt.addItem("Injection");
    mt.addItem("Capsule");
    mp.setText("");
    mq.setText("");
}
private void edit(boolean x){
    mid.setEditable(x);
    //mn.setEditable(x);
    custid.setEditable(x);
    //cn.setEditable(x);
    //mt.setEditable(x);
    //mp.setEditable(x);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        edit(true);
        tpfield.setEditable(false);
        int cid = 0;
        int chid=0;
        cuid = custid.getText();
        custid.setEditable(false);
        String medid = mid.getText();
        if(cuid.equals("")){
            JOptionPane.showMessageDialog(null, "Customer id field is required");
        } 
        else if(medid.equals("")){
            JOptionPane.showMessageDialog(null, "Medicine id field is required");
        } else{
            try{
                Connection con = Connecter.getCon();
                Statement st = con.createStatement();
                ResultSet rs  = st.executeQuery("select points from customer where id = '"+cuid+"'");
                //JOptionPane.showMessageDialog(null, "Medicine id field is required");
                if(rs.next()){
                 chid=1;
                 pts = rs.getInt("points");
                 rs = st.executeQuery("select * from drugs where id = '"+medid+"'");
                while(rs.next()){
                    edit(false);
                    cid = 1;
                    mn.setText(rs.getString("drug_name"));
                    cn.setText(rs.getString("company_name"));
                    mp.setText(rs.getString("price"));
                    if(rs.getString("drug_type").equals("Tablet")) {
                        mt.removeAllItems();
                        mt.addItem("Tablet");
                        mt.addItem("Syrup");
                        mt.addItem("Injection");
                        mt.addItem("Capsule");
                    }
                    else if(rs.getString("drug_type").equals("Syrup")){
                        mt.removeAllItems();
                        mt.addItem("Syrup");
                        mt.addItem("Tablet");
                        mt.addItem("Injection");
                        mt.addItem("Capsule");
                    }else if(rs.getString("drug_type").equals("Injection")){
                        mt.removeAllItems();
                        mt.addItem("Injection");
                        mt.addItem("Syrup");
                        mt.addItem("Tablet");
                        mt.addItem("Capsule");
                    }else{
                        mt.removeAllItems();
                        mt.addItem("Capsule");
                        mt.addItem("Injection");
                        mt.addItem("Syrup");
                        mt.addItem("Tablet");
                        }
                    cn.setEditable(false);
                    mn.setEditable(false);
                    mt.setEditable(false);
                    mp.setEditable(false);
                    uid=cuid;
                }
        }  
}catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
}
        if(chid==0){
            JOptionPane.showMessageDialog(null,"Customer id does not exist");
        }
            if(cid == 0){
                JOptionPane.showMessageDialog(null,"Medicine id does not exist");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String md = mid.getText();
        String mname = mn.getText();
        String cuid = custid.getText();
        String mcname = cn.getText();
        String mtp = (String)mt.getSelectedItem();
        double pric = Float.parseFloat(mp.getText());
        String units = mq.getText();
        int cs=0;
        if(md.equals("") || cuid.equals("")){
            JOptionPane.showMessageDialog(null,"Empty Field");
        }else{
        if(units.equals("")){
              JOptionPane.showMessageDialog(null,"No. of Units is a must Field");
        }else{
            try{
            Connection con = Connecter.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from drugs where id = '"+md+"'");
            while(rs.next()){
                if(rs.getInt("quantity")>= Integer.parseInt(units)){
                    cs=1;
                }else{
                    JOptionPane.showMessageDialog(null,"Medicine is out of Stock.");
                }
            }
            }catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(cs==1){
                double uni = Float.parseFloat(units);
                double z = uni*pric;
                double x = Float.parseFloat(String.format("%.2f", z));
                DefaultTableModel m = (DefaultTableModel)cart.getModel();
                m.addRow(new Object[] {cuid,md,mname,mcname,pric,units,x});
                tp+=x;
                tpfield.setText(String.valueOf(tp));
                JOptionPane.showMessageDialog(null,"Added to Cart");
                clearmed();
                edit(true);
            }
            
            
        }}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartMouseClicked
        // TODO add your handling code here:
        int i = cart.getSelectedRow();
        int x = JOptionPane.showConfirmDialog(null,"Do you Want to Remove the Specific Medicine","Select",JOptionPane.YES_NO_OPTION);
        if(x==0){
                TableModel m = cart.getModel();
                String tot= m.getValueAt(i,6).toString();
                tp-=Float.parseFloat(tot);
                tpfield.setText(String.valueOf(tp));
                ((DefaultTableModel)cart.getModel()).removeRow(i);
        }
    }//GEN-LAST:event_cartMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null,"Do You Want to Use Your Points to Get Discount?\nCurrent Points : "+pts,"Select",JOptionPane.YES_NO_OPTION);
        if(tp>500){pts=pts+10;}
        if(tp!=0){
            DefaultTableModel t = (DefaultTableModel)cart.getModel();
            if(cart.getRowCount()!=0){
                for(int i=0;i<cart.getRowCount();i++){
                    try{
                         Connection con = Connecter.getCon();
                         Statement st = con.createStatement();
                         String qty = String.valueOf(t.getValueAt(i,5));
                         String idd = String.valueOf(t.getValueAt(i,1));
                         st.executeUpdate("update drugs set quantity=quantity-"+qty+" where id = "+idd);
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
            try{
                SimpleDateFormat mf = new SimpleDateFormat("dd-MM-yyyy");
                Calendar ca = Calendar.getInstance();
                Connection con = Connecter.getCon();
                var ps = con.prepareStatement("insert into bill(billdate,totalpaid,customer_id) values(?,?,?)",Statement.RETURN_GENERATED_KEYS);
                //ps.setString(1, bid);
                ps.setString(1, mf.format(ca.getTime()));
                ps.setString(2, String.valueOf(tp));
                //ps.setString(4, un);
                ps.setString(3,uid);
                ps.executeUpdate();
                Statement st = con.createStatement();
                ResultSet rs = ps.getGeneratedKeys();
                if (rs.next()) { 
                    bid = rs.getString(1); 
                } else {   
                    bid = null; 
                }
                 JOptionPane.showMessageDialog(null, "Generating Bill...");
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            if(x==0){
                tp=tp-(tp*(pts/10)*0.01);
                try {
                    Connection con = Connecter.getCon();
                    Statement st = con.createStatement();
                    st.executeUpdate("update customer set points = 0 where id = " + cuid);
                }catch(Exception e){JOptionPane.showMessageDialog(null, e);}       
            }
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try{
            PdfWriter.getInstance(doc, new FileOutputStream(Loco.path+""+bid+".pdf"));
            doc.open();
            Paragraph p = new Paragraph("                                                                SHANTHI MEDICALS\n");
            doc.add(p);
            Paragraph sep = new Paragraph("\n---------------------------------------------------------------------------------------------------------------------\n");
            doc.add(sep);
            Paragraph det = new Paragraph("\tBill ID : "+bid+"\nCustomer ID : "+uid+"\nDate : "+new Date());
            doc.add(det);
            PdfPTable tab = new PdfPTable(6);
            doc.add(sep);
            tab.addCell("Medicine ID");
            tab.addCell("Name");
            tab.addCell("Company Name");
            tab.addCell("Price/Unit");
            tab.addCell("Total Units"); 
            tab.addCell("Total Price");
            for(int i=0;i<cart.getRowCount();i++){
                String  c1 = cart.getValueAt(i,1).toString();
                String  c2 = cart.getValueAt(i,2).toString();
                String  c3 = cart.getValueAt(i,3).toString();
                String  c4 = cart.getValueAt(i,4).toString();
                String  c5 = cart.getValueAt(i,5).toString();
                String  c6 = cart.getValueAt(i,6).toString();
                tab.addCell(c1);
                tab.addCell(c2);
                tab.addCell(c3);
                tab.addCell(c4);
                tab.addCell(c5);
                tab.addCell(c6);
                
            }
            doc.add(tab);
            doc.add(sep);
            Paragraph q = new Paragraph("                       Final Price : "+tp);
            doc.add(q);
            Open.openById(String.valueOf(bid));
            
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
            setVisible(false);
            new SellMedicine(un).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Add Some Medicine Before Printing");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
setVisible(false);
       //  new PharmacistDashboard().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cart;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField custid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField mn;
    private javax.swing.JTextField mp;
    private javax.swing.JTextField mq;
    private javax.swing.JComboBox<String> mt;
    private javax.swing.JTextField tpfield;
    // End of variables declaration//GEN-END:variables
}
