
import dao.Connecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yokes
 */
public class Ucustomer extends javax.swing.JFrame {
    private String ep = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    private String mp = "^[0-9]{10}$";

    /**
     * Creates new form Ucustomer
     */
    public Ucustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        ca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ce = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 18, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 1015, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 144, 37, -1));
        getContentPane().add(cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 148, 258, -1));

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 148, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 228, -1, -1));
        getContentPane().add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 271, 201, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 333, -1, -1));
        getContentPane().add(cm, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 376, 201, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 448, 63, -1));
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 501, 201, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 228, 84, -1));
        getContentPane().add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 271, 201, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 333, 71, -1));
        getContentPane().add(ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 376, 201, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 491, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int chid = 0;
        String ckid = cid.getText();
        if(ckid.equals("")){
            JOptionPane.showMessageDialog(null, "id field is required");
        } else{
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            try{
                Connection con = Connecter.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from customer where id = '"+ckid+"'");
                while(rs.next()){
                    cid.setEditable(false);
                    chid = 1;
                    cn.setText(rs.getString("name"));
                    cm.setText(rs.getString("mobile"));
                    ce.setText(rs.getString("email"));
                    ca.setText(rs.getString("address"));
                    String date = rs.getString("dob");
                    if(date!= ""){
                        try{
                            dob.setDate(dFormat.parse(date));
                        }
                        catch(Exception e){ }
                    }
                                    }
        }   catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(chid == 0){
                JOptionPane.showMessageDialog(null,"id does not exist");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int ckid = Integer.parseInt(cid.getText());
        String name = cn.getText();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        Date date = dob.getDate();
        String daob ="";
        if(date != null){
            daob = formatter.format(dob.getDate());
        }
        String mobileNumber = cm.getText();
        String email = ce.getText();
        String address = ca.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Name field is required.");
        } else if(daob.equals("")){
            JOptionPane.showMessageDialog(null,"Date of Birth field is required.");
        } else if(mobileNumber.equals("")){
            JOptionPane.showMessageDialog(null,"Mobile Number field is required.");
        } else if(!mobileNumber.matches(mp) || mobileNumber.length() !=10){
            JOptionPane.showMessageDialog(null,"Mobile Number field is invalid.");
        } else if(!email.matches(ep)){
            JOptionPane.showMessageDialog(null,"Email field is invalid.");
        } else if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Email field is required.");
        } else if(address.equals("")){
            JOptionPane.showMessageDialog(null,"Address field is required");
        } else{
            try {
    Connection con = Connecter.getCon();
    PreparedStatement ps = con.prepareStatement("UPDATE customer SET name=?, dob=?, mobile=?, email=?, address=? WHERE id=?");
    ps.setString(1, name);
    ps.setString(2, daob);
    ps.setString(3, mobileNumber);
    ps.setString(4, email);
    ps.setString(5, address);
    ps.setInt(6, ckid);
    int rowsAffected = ps.executeUpdate(); 
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Customer Updated Successfully");
        setVisible(false);
        new Ucustomer().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Update failed. No matching id found.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
setVisible(false);
         //new PharmacistDashboard().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ucustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ucustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ucustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ucustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ucustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca;
    private javax.swing.JTextField ce;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cm;
    private javax.swing.JTextField cn;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
