
import dao.Connecter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yokes
 */
public class Umedicine extends javax.swing.JFrame {
        public String quanp = "^[1-9]\\d*$";


    /**
     * Creates new form Umedicine
     */
    public Umedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        mid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mt = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        qt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("UPDATE MEDICINE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 27, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, 961, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Medicine id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 137, -1, -1));
        getContentPane().add(mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 141, 262, -1));

        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 141, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Medicine Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 225, -1, -1));
        getContentPane().add(mn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 268, 195, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Medicine Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 225, 134, -1));

        mt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tablet", "Syrup", "Injection", "Capsule" }));
        getContentPane().add(mt, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 268, 198, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Company Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 348, -1, 17));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Price/Unit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 344, -1, -1));
        getContentPane().add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 387, 195, -1));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 387, 198, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 527, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 484, -1, -1));
        getContentPane().add(qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 527, 183, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(941, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int cmed = 0;
        String medid = mid.getText();
        if(mid.equals("")){
            JOptionPane.showMessageDialog(null, "Medicine ID field is required");
        } else{
            try{
                Connection con = Connecter.getCon();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from drugs where id = '"+medid+"'");
                while(rs.next()){
                    mid.setEditable(false);
                    cmed = 1;
                    mn.setText(rs.getString("drug_name"));
                    cn.setText(rs.getString("company_name"));
                    price.setText(rs.getString("price"));
                    qt.setText(String.valueOf(rs.getInt("quantity")));

                    if(rs.getString("drug_type").equals("Tablet")) {
                        mt.removeAllItems();
                        mt.addItem("Tablet");
                        mt.addItem("Syrup");
                        mt.addItem("Injection");
                        mt.addItem("Capsule");
                    }
                    else if(rs.getString("drug_type").equals("Syrup")){
                        mt.removeAllItems();
                        mt.addItem("Syrup");
                        mt.addItem("Tablet");
                        mt.addItem("Injection");
                        mt.addItem("Capsule");
                    }else if(rs.getString("drug_type").equals("Injection")){
                        mt.removeAllItems();
                        mt.addItem("Injection");
                        mt.addItem("Syrup");
                        mt.addItem("Tablet");
                        mt.addItem("Capsule");
                    }else{
                        mt.removeAllItems();
                        mt.addItem("Capsule");
                        mt.addItem("Injection");
                        mt.addItem("Syrup");
                        mt.addItem("Tablet");
                        }
                }
        }   catch(Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            if(cmed == 0){
                JOptionPane.showMessageDialog(null,"Medicine ID does not exist");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String mtype = (String) mt.getSelectedItem();
        String mname = mn.getText();
        String cname = cn.getText();
        String medid = mid.getText();
        String pric = price.getText();
        String q = qt.getText();
        if(medid.equals("")){
            JOptionPane.showMessageDialog(null,"ID field is required.");
        } else if(mname.equals("")){
            JOptionPane.showMessageDialog(null,"Medicine Name field is required.");
        } else if(cname.equals("")){
            JOptionPane.showMessageDialog(null,"Company Name field is required.");
        } else if(pric.equals("")){
            JOptionPane.showMessageDialog(null,"Price field is required.");
        } else if(q.equals("")){
            JOptionPane.showMessageDialog(null,"Quantity field is required.");
        }else if(!q.matches(quanp)){
            JOptionPane.showMessageDialog(null,"Quantity field is Inavlid.");
        }  else{
            try {
    Connection con = Connecter.getCon();
    float p = Float.parseFloat(pric);
    int t = Integer.parseInt(medid);
    int z = Integer.parseInt(q);
    PreparedStatement ps = con.prepareStatement("UPDATE drugs SET drug_name=?, drug_type=?, company_name=?, price=?, quantity = ? WHERE id=?");
    ps.setString(1, mname);
    ps.setString(2, mtype);
    ps.setString(3, cname);
    ps.setFloat(4, p);
    ps.setInt(5, z);
    ps.setInt(6, t);
    int rowsAffected = ps.executeUpdate(); 
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Medicine Updated Successfully");
        setVisible(false);
        new Umedicine().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Update failed. No matching id found.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
setVisible(false);
       //  new PharmacistDashboard().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Umedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Umedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Umedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Umedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Umedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mid;
    private javax.swing.JTextField mn;
    private javax.swing.JComboBox<String> mt;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qt;
    // End of variables declaration//GEN-END:variables
}
